=== solixoi/sitairis7-9/src/main/resources/validator.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
    <xs:element name="users" type ="users"/>

    <xs:complexType name="users">
        <xs:sequence>
            <xs:element name="user" type="user" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="user">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="orders" type="orders" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="orders">
        <xs:sequence>
            <xs:element name="order" type="order" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="order">
        <xs:sequence>
            <xs:element name="car_name" type="xs:string"/>
            <xs:element name="car_price" type="xs:double"/>
            <xs:element name="buy_date" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"  use="required"/>
    </xs:complexType>
</xs:schema>

=== solixoi/sitairis7-9/src/main/resources/users_xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validator.xsd">
    <user id="1">
        <name>dsadasd</name>
        <orders>
            <order id="1">
                <car_name>Add</car_name>
                <car_price>123</car_price>
                <buy_date>2000-10-10</buy_date>
            </order>
        </orders>
    </user>
</users>
